markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Doug Burman 
url: http://pourfac.es
description: A fantastic blog that is fantastic.
twitter: therapod 
github: dburman 
gravatar_url: http://gravatar.com/avatar/601c895402e2655fc3fd00d225e18457
